### ISSUE TITLE
Can't create events 

### ISSUE THREAD

**Issue by masterofeye** [owncloud/calendar-rework#71]
### Steps to reproduce
clean install on raspberry pi
### Expected behaviour
Normal creation of events through the web interface

### Actual behaviour
After "save Event" nothing is happend.

### Server configuration
**Operating system**:
Rasbian OS
**Web server:**
Apache2
**Database:**
SQLLite
**PHP version:**
5.5
**ownCloud version:** (see ownCloud admin page)
newest
**Updated from an older ownCloud or fresh install:**
fresh install
**List of activated apps:**
only the calender rework 

no changes in config.php

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Chrome/Firefox
**Operating system:**
Rasbian
#### Web server error log
no logs
Insert your webserver log here
no intersting logs
#### ownCloud log (data/owncloud.log)
Insertour ownCloud log here
no logs
#### Browser log
no errors

**Comment by georgehrke** [comment]
dup of https://github.com/owncloud/calendar-rework/issues/11

Just to be sure: this is a very early development version. Never ever use this in production.
